import type { FreelancerWithProfile } from "@/types";

export const MOCK_FREELANCERS: FreelancerWithProfile[] = [
  {
    id: "mock-1",
    clerkId: "clerk-1",
    email: "yuki@craftlink.demo",
    name: "Yuki Tanaka",
    role: "FREELANCER",
    avatarUrl: null,
    bio: "Minimalist brand designer inspired by wabi-sabi aesthetics.",
    createdAt: new Date(),
    updatedAt: new Date(),
    freelancerProfile: {
      id: "fp-1",
      userId: "mock-1",
      title: "Brand & Identity Designer",
      tagline: "Crafting calm, timeless brands",
      skills: ["Brand Identity", "Logo Design", "Typography"],
      categories: ["Brand Design", "Graphic Design"],
      hourlyRate: 85,
      location: "Tokyo, Japan",
      yearsExperience: 8,
      isAvailable: true,
      revisionPolicy: "2 rounds per milestone",
      responseTime: "< 2 hours",
      totalOrders: 124,
      rating: 4.9,
      reviewCount: 98,
      createdAt: new Date(),
      updatedAt: new Date(),
      portfolioItems: [
        {
          id: "p1",
          profileId: "fp-1",
          title: "Sakura Tea Brand",
          description: "Complete brand identity",
          imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
          category: "Brand Design",
          tags: ["branding", "packaging"],
          sortOrder: 0,
          createdAt: new Date(),
        },
        {
          id: "p2",
          profileId: "fp-1",
          title: "Zen Wellness",
          description: "Logo & visual system",
          imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&q=80",
          category: "Brand Design",
          tags: ["logo", "minimal"],
          sortOrder: 1,
          createdAt: new Date(),
        },
        {
          id: "p3",
          profileId: "fp-1",
          title: "Artisan Ceramics",
          description: "Packaging design",
          imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&q=80",
          category: "Packaging",
          tags: ["packaging"],
          sortOrder: 2,
          createdAt: new Date(),
        },
      ],
      servicePackages: [
        {
          id: "s1",
          profileId: "fp-1",
          title: "Logo Essentials",
          description: "Primary logo, variations, and brand guidelines PDF.",
          price: 450,
          deliveryDays: 7,
          revisions: 2,
          features: ["3 concepts", "Vector files", "Color palette"],
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: "s2",
          profileId: "fp-1",
          title: "Full Brand Identity",
          description: "Complete visual identity system for your business.",
          price: 1200,
          deliveryDays: 14,
          revisions: 3,
          features: ["Logo suite", "Typography", "Brand book", "Social templates"],
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    },
  },
  {
    id: "mock-2",
    clerkId: "clerk-2",
    email: "mei@craftlink.demo",
    name: "Mei Chen",
    role: "FREELANCER",
    avatarUrl: null,
    bio: "Illustrator specializing in delicate line art and editorial work.",
    createdAt: new Date(),
    updatedAt: new Date(),
    freelancerProfile: {
      id: "fp-2",
      userId: "mock-2",
      title: "Illustrator & Visual Artist",
      tagline: "Stories told through delicate lines",
      skills: ["Illustration", "Editorial", "Character Design"],
      categories: ["Illustration", "Graphic Design"],
      hourlyRate: 70,
      location: "Shanghai, China",
      yearsExperience: 6,
      isAvailable: true,
      revisionPolicy: "Unlimited minor tweaks",
      responseTime: "< 4 hours",
      totalOrders: 89,
      rating: 4.8,
      reviewCount: 72,
      createdAt: new Date(),
      updatedAt: new Date(),
      portfolioItems: [
        {
          id: "p4",
          profileId: "fp-2",
          title: "Botanical Series",
          description: "Watercolor-inspired digital illustrations",
          imageUrl: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
          category: "Illustration",
          tags: ["botanical", "editorial"],
          sortOrder: 0,
          createdAt: new Date(),
        },
        {
          id: "p5",
          profileId: "fp-2",
          title: "Literary Magazine",
          description: "Cover and spot illustrations",
          imageUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
          category: "Illustration",
          tags: ["editorial"],
          sortOrder: 1,
          createdAt: new Date(),
        },
      ],
      servicePackages: [
        {
          id: "s3",
          profileId: "fp-2",
          title: "Custom Illustration",
          description: "One bespoke illustration for print or digital.",
          price: 280,
          deliveryDays: 5,
          revisions: 2,
          features: ["High-res PNG", "Source file", "Commercial license"],
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    },
  },
  {
    id: "mock-3",
    clerkId: "clerk-3",
    email: "haruto@craftlink.demo",
    name: "Haruto Sato",
    role: "FREELANCER",
    avatarUrl: null,
    bio: "Web designer creating serene, conversion-focused interfaces.",
    createdAt: new Date(),
    updatedAt: new Date(),
    freelancerProfile: {
      id: "fp-3",
      userId: "mock-3",
      title: "Web & UI Designer",
      tagline: "Digital spaces that breathe",
      skills: ["Web Design", "Figma", "UI/UX"],
      categories: ["Web Design", "UI/UX Design"],
      hourlyRate: 95,
      location: "Osaka, Japan",
      yearsExperience: 10,
      isAvailable: true,
      revisionPolicy: "Structured milestone reviews",
      responseTime: "< 1 hour",
      totalOrders: 156,
      rating: 5.0,
      reviewCount: 112,
      createdAt: new Date(),
      updatedAt: new Date(),
      portfolioItems: [
        {
          id: "p6",
          profileId: "fp-3",
          title: "Boutique E-commerce",
          description: "Full storefront UI design",
          imageUrl: "https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?w=800&q=80",
          category: "Web Design",
          tags: ["ecommerce", "ui"],
          sortOrder: 0,
          createdAt: new Date(),
        },
      ],
      servicePackages: [
        {
          id: "s4",
          profileId: "fp-3",
          title: "Landing Page Design",
          description: "Single high-converting landing page in Figma.",
          price: 650,
          deliveryDays: 10,
          revisions: 3,
          features: ["Desktop + mobile", "Design system", "Dev handoff"],
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
    },
  },
];

export function getMockFreelancer(id: string) {
  return MOCK_FREELANCERS.find((f) => f.id === id) ?? null;
}
